# For You
- name: create user
  user:
    name: "{{ user_name_jankins }}"
    shell: /bin/bash
    group: sudo
    create_home: yes

- name: create ssh directory
  file:
    path: /home/{{ user_name_jankins }}/.ssh
    state: directory

- name: Copy id_rsa.pub from local to remote_user directory
  copy:
    src: "~/.ssh/id_rsa.pub"
    dest: "/home/{{ user_name_jankins }}/.ssh/authorized_keys"

- name: Add users to /etc/sudoers
  lineinfile:
    path: "/etc/sudoers"
    line: '{{ item }} ALL=(ALL) NOPASSWD:ALL'
    state: present
    insertafter: EOF
  with_items:
    - "{{ user_name_jankins }}"
    - "jenkins"
  
- name: Check if SSH key already exists
  stat:
    path: "/home/ubuntu/.ssh/id_rsa.pub"
  register: ssh_key

- name: Generate SSH key with 4096 bits if it doesn't exist
  command: ssh-keygen -t rsa -b 4096 -f /home/ubuntu/.ssh/id_rsa -N ""
  when: not ssh_key.stat.exists


# For adding teammate enable this section if you want to do so.
# - name: create user
#   user:
#     name: "{{ teammate }}"
#     shell: /bin/bash
#     group: sudo
#     create_home: yes

# - name: create ssh directory
#   file:
#     path: /home/{{ teammate }}/.ssh
#     state: directory

# - name: copy teammate id_rsa.pub key to remote server authorized_keys
#   copy:
#     src: teammate-id_rsa.pub
#     dest: /home/{{ teammate }}/.ssh/authorized_keys

# - name: Add user to /etc/sudoers
#   lineinfile:
#     path: "/etc/sudoers"
#     line: '{{ teammate }} ALL=(ALL) NOPASSWD:ALL'
#     state: present
#     insertafter: EOF
