global:
  resolve_timeout: 5s

route:
  receiver: 'slack'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
- name: 'slack'
  slack_configs:
  - channel: "#project"  # Make sure this matches your Slack channel name
    send_resolved: true
    api_url: 'https://hooks.slack.com/services/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'
    icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
    text: >-
      {{ range .Alerts -}}
      *Alert:* {{ .Annotations.summary }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

      *Description:* {{ .Annotations.description }}

      *Details:*
        {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}
